function(GetGitInfo GitHash GitCount)
	find_package(Git QUIET)
	if(GIT_FOUND)
		execute_process(
			COMMAND ${GIT_EXECUTABLE} describe --tags --abbrev=0
			WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
			OUTPUT_VARIABLE GIT_LAST_TAG
			OUTPUT_STRIP_TRAILING_WHITESPACE
			ERROR_QUIET
			RESULT_VARIABLE TAG_RESULT
		)

		if(TAG_RESULT EQUAL 0)
			execute_process(
				COMMAND ${GIT_EXECUTABLE} rev-list --count ${GIT_LAST_TAG}..HEAD
				WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
				OUTPUT_VARIABLE RAW_GIT_COMMIT_COUNT
				OUTPUT_STRIP_TRAILING_WHITESPACE
				ERROR_QUIET
			)
		else()
			execute_process(
				COMMAND ${GIT_EXECUTABLE} rev-list --count HEAD
				WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
				OUTPUT_VARIABLE RAW_GIT_COMMIT_COUNT
				OUTPUT_STRIP_TRAILING_WHITESPACE
				ERROR_QUIET
			)
		endif()


		execute_process(
			COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD
			WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
			OUTPUT_VARIABLE RAW_GIT_COMMIT_HASH
			OUTPUT_STRIP_TRAILING_WHITESPACE
			ERROR_QUIET
		)

		set(${GitHash} "${RAW_GIT_COMMIT_HASH}" PARENT_SCOPE)
		set(${GitCount} "\"${RAW_GIT_COMMIT_COUNT}\"" PARENT_SCOPE)




	endif()
endfunction()
