function(ParseVersion header)
    file(READ "${header}" rawfile)
    foreach(var MAJOR MINOR PATCH)
        string(REGEX MATCH 
                "#define PANKTI_VERSION_${var}[ \t]+([0-9]+)" _ ${rawfile})

        if(CMAKE_MATCH_1 STREQUAL "")
            message(FATAL_ERROR 
                "ParseVersion(..) could not find #define PANKTI_VERSION_${var}")
        endif()
        set(PANKTI_VERSION_${var} ${CMAKE_MATCH_1})
    endforeach()

    string(REGEX MATCH 
        "#define PANKTI_RELEASE_LEVEL[ \t]+\"([^\"]*)\"" _ ${rawfile})
    if(CMAKE_MATCH_1 STREQUAL "")
        set(PANKTI_RELEASE_LEVEL "")
    else()
        set(PANKTI_RELEASE_LEVEL "${CMAKE_MATCH_1}")
    endif()
	if(NOT PANKTI_RELEASE_LEVEL STREQUAL "")
		set(PANKTI_VERSION_STRING
			"${PANKTI_VERSION_MAJOR}.${PANKTI_VERSION_MINOR}.${PANKTI_VERSION_PATCH}-${PANKTI_RELEASE_LEVEL}")
	else()
		set(PANKTI_VERSION_STRING
			"${PANKTI_VERSION_MAJOR}.${PANKTI_VERSION_MINOR}.${PANKTI_VERSION_PATCH}")
	endif()
	
    if(NOT NO_GIT_INFO)
		if((NOT PANKTI_GIT_HASH STREQUAL "_") AND (NOT PANKTI_GIT_COUNT STREQUAL ""))
			string(REPLACE "\"" "" PANKTI_GIT_COUNT_CLEAN "${PANKTI_GIT_COUNT}")
			set(PANKTI_VERSION_FULL "${PANKTI_VERSION_STRING}.r${PANKTI_GIT_COUNT_CLEAN}+${PANKTI_GIT_HASH}")
		else()
			set(PANKTI_VERSION_FULL "${PANKTI_VERSION_STRING}")
		endif()
	else()
		set(PANKTI_VERSION_FULL "${PANKTI_VERSION_STRING}")
	endif()

	set(PANKTI_VERSION_MAJOR ${PANKTI_VERSION_MAJOR} PARENT_SCOPE)
	set(PANKTI_VERSION_MINOR ${PANKTI_VERSION_MINOR} PARENT_SCOPE)
	set(PANKTI_VERSION_PATCH ${PANKTI_VERSION_PATCH} PARENT_SCOPE)
    set(PANKTI_RELEASE_LEVEL ${PANKTI_RELEASE_LEVEL} PARENT_SCOPE)
	set(PANKTI_VERSION_STRING ${PANKTI_VERSION_STRING} PARENT_SCOPE)
	set(PANKTI_VERSION_FULL ${PANKTI_VERSION_FULL} PARENT_SCOPE)
	set(PANKTI_GIT_COUNT_CLEAN ${PANKTI_GIT_COUNT_CLEAN} PARENT_SCOPE)
endfunction()
