#ifndef KEYWORDS_H
#define KEYWORDS_H

#define KW_EN_LET "let"
#define KW_EN_AND "and"
#define KW_EN_OR "or"
#define KW_EN_END "end"
#define KW_EN_IF "if"
#define KW_EN_THEN "then"
#define KW_EN_ELSE "else"
#define KW_EN_WHILE "while"
#define KW_EN_NIL "nil"
#define KW_EN_TRUE "true"
#define KW_EN_FALSE "false"
#define KW_EN_RETURN "return"
#define KW_EN_FUNC "func"
#define KW_EN_IMPORT "import"
#define KW_EN_PANIC "panic"
#define KW_EN_DO "do"
#define KW_EN_BREAK "break"
#define KW_EN_LEN "len"
#define KW_EN_PRINT "print"

#define KW_PN_LET "dhori"
#define KW_PN_AND "ebong"
#define KW_PN_OR "ba"
#define KW_PN_END "sesh"
#define KW_PN_IF "jodi"
#define KW_PN_THEN "tahole"
#define KW_PN_ELSE "nahole"
#define KW_PN_WHILE "jotokhon"
#define KW_PN_NIL "nil"
#define KW_PN_TRUE "sotti"
#define KW_PN_FALSE "mittha"
#define KW_PN_RETURN "ferao"
#define KW_PN_FUNC "kaj"
#define KW_PN_IMPORT "anoyon"
#define KW_PN_PANIC "golmal"
#define KW_PN_DO "koro"
#define KW_PN_BREAK "bhango"
#define KW_PN_LEN "ayoton"
#define KW_PN_PRINT "print"

#define KW_BN_LET "ধরি"
#define KW_BN_AND "এবং"
#define KW_BN_OR "বা"
#define KW_BN_END "শেষ"
#define KW_BN_IF "যদি"
#define KW_BN_THEN "তাহলে"
#define KW_BN_ELSE "নাহলে"
#define KW_BN_WHILE "যতক্ষণ"
#define KW_BN_NIL "নিল"
#define KW_BN_TRUE "সত্যি"
#define KW_BN_FALSE "মিথ্যা"
#define KW_BN_RETURN "ফেরাও"
#define KW_BN_FUNC "কাজ"
#define KW_BN_IMPORT "আনয়ন"
#define KW_BN_PANIC "গোলমাল"
#define KW_BN_DO "করো"
#define KW_BN_BREAK "ভাঙো"
#define KW_BN_LEN "আয়তন"
#define KW_BN_PRINT "print"

#endif
